[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "viscofit"
version = "0.1.0"
description = "Calibration of Lennard-Jones parameters to reproduce viscosities of aqueous strong electrolyte mixtures using experimental data collected from the literature."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "João Lucas H. Detogni"}
]

dependencies = [
    "polars[excel]==1.42.0",
    "optuna==3.6.1",
    "coolname==5.0.0",
    "tqdm==4.68.4",
    "questionary==2.1.1"
]
requires-python = ">=3.12"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["viscofit*"]
